### ISSUE TITLE
Aurelia Store for state management

### ISSUE THREAD

**Issue by Vheissu** [bigopon/aurelia-monopoly#2]
I've used the Aurelia Store plugin a bit for my state management needs and I think a game like this lends itself to proper state management (recording turns, buying property, etc). Thoughts? https://github.com/aurelia/store

**Comment by bigopon** [comment]
While there is no need for the core game to have the ability to undo, redo, a logging system of all stuff happens in the game is essential, so a single store synced between server / client should be good to debug / replay ?

**Comment by Vheissu** [comment]
@bigopon Absolutely. The state management will just ensure that when a move is recorded for example, that it adds a new entry into the state history/tree and gives us the immutability of a game that can't be easily tampered with or accidentally overwritten because of Javascript's lovely design feature of passing everything by reference.
